# Generated by Django 4.2.5 on 2023-10-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw02app', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'активный'), ('complete', 'завершенный'), ('canceled', 'отмененный')], default='active', max_length=12),
        ),
    ]
